title: OmniHelp
author: Joanne Yeung
email: joanne@omnibuilds.com
site: https://www.omnibuilds.com
description: > # this means to ignore newlines until "baseurl:"
  A help guide for OmniBuilds.com.

# twitter_username:
github_username: jttyeung

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
# - README.md
# - omnibuilds.md

# Link slug for each help article
permalink: /articles/:title/

# category_weights: ['Account Settings', 'Getting Started']

category_weights: [
  'Getting Started',
  'Exploring Designs on OmniBuilds',
  'Account Settings',
]
  # 'Account Settings':
  #   weight: 2

  # 'Getting Started':
  #   weight: 1

  # 'Exploring Designs on OmniBuilds':
  #   weight: 3


# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

# Plugins
plugins: ['jekyll-lunr-js-search', 'jekyll-octicons']

# Analytics
google_analytics: UA-105971114-1

lunr_search:
  js_dir: "assets/js/"
