title: OmniHelp
author: Jeremiah Wagstaff
email: jeremiah@omnibuilds.com
site: https://www.omnibuilds.com
description: > # this means to ignore newlines until "baseurl:"
  A help guide for OmniBuilds.com.

# twitter_username:
github_username: jwagstaff

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - index.md
# - omnibuilds.md

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
