title: OmniHelp
author: Jeremiah Wagstaff
email: jeremiah@omnibuilds.com
site: https://www.omnibuilds.com
description: > # this means to ignore newlines until "baseurl:"
  A help guide for OmniBuilds.com.

# twitter_username:
github_username: jwagstaff

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
# - README.md
# - omnibuilds.md

# Link slug for each help article
permalink: /articles/:title/

category_weights:
  # values:
    2: "Getting Started"
    1: "Login & Registration"

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

# Plugins
# plugins:
  # -

#Gems
gems: ['jekyll-lunr-js-search']

# Analytics
google_analytics: UA-105971114-1
